SELECT CONCAT (Name, '(',SUBSTR(OCCUPATION,1,1),')') as NameOccupation
From OCCUPATIONS
Order by NameOccupation;

SELECT CONCAT('There are a total of ',COUNT(OCCUPATION),' ',LOWER(OCCUPATION),'s.')
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;